config/routes.rb
AtagSummitFS::Application.routes.draw do

  resources :categories

  get "home/index"

  get "login" => "login#login"
  get "registro" => "login#registro"
  post "registrar" => "login#registrar"
  post "ingreso" => "login#ingreso"
  get "salir" => "login#salir"
  resources :articulos
  resources :autores

  root :to => "home#index"

  get "show" => "home#show"
  post "agregar_comentario" => "articulos#agregar_comentario"
  
  get "show_autor" => "autor#show"

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
  belongs_to :autor
  has_and_belongs_to_many :categories
  has_many :comments, :dependent => :destroy
  has_many :hits
end

app/models/autor.rb
class Autor < ActiveRecord::Base
	has_many :articulos
	validates_presence_of :usuario, :nombre
	validates_uniqueness_of :usuario
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articulos
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :articulo
  validates_presence_of :comentador, :cuerpo
end

app/models/hit.rb
class Hit < ActiveRecord::Base
  belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.where(:autor_id => session[:autor_id]).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articulos }
    end
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
    @articulo = Articulo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @articulo }
    end
  end

  # GET /articulos/new
  # GET /articulos/new.json
  def new
    @articulo = Articulo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @articulo }
    end
  end

  # GET /articulos/1/edit
  def edit
    @articulo = Articulo.find(params[:id])
    @comment_ids_before_edition = @articulo.comment_ids
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(params[:articulo])

    if session[:autor_id].nil?
      redirect_to login_path
    else  
      @articulo.autor_id= session[:autor_id]

      respond_to do |format|
        if @articulo.save
          format.html { redirect_to @articulo, notice: 'Articulo creado exitosamente' }
          format.json { render json: @articulo, status: :created, location: @articulo }
        else
          format.html { render action: "new" }
          format.json { render json: @articulo.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  # PUT /articulos/1
  # PUT /articulos/1.json
  def update
    @articulo = Articulo.find(params[:id])

		if (not params[:articulo][:comment_ids].nil?)
	    #apologies for the hack, couldnt find a better way to do it
	    comment_ids_after_edition = params[:comment_ids_before_edition].split.keep_if do |comment_id| (not params[:articulo][:comment_ids].include? comment_id)
    	end
	    params[:articulo][:comment_ids] = comment_ids_after_edition
		end
		
    respond_to do |format|
      if @articulo.update_attributes(params[:articulo])
        format.html { redirect_to @articulo, notice: 'Articulo actualizado exitosamente' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo = Articulo.find(params[:id])
    @articulo.destroy

    respond_to do |format|
      format.html { redirect_to articulos_url }
      format.json { head :ok }
    end
  end

  
  def agregar_comentario
    @comentario = Comment.new(params[:comment])
    @comentario.articulo_id = params[:articulo_id]

    if @comentario.save
      redirect_to :controller => "home", :action => "show", :id => @comentario.articulo_id
    else
      redirect_to :back, :notice => "No se pudo agregar el comentario, el nombre y cuerpo deben ser completados" 
    end
  end

end

app/controllers/autor_controller.rb
class AutorController < ApplicationController

  # GET /autores/1
  # GET /autores/1.json
  def show
    @autor = Autor.find(params[:id])

    respond_to do |format|
      format.html # show_autor.html.erb
      format.json { render json: @autor }
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articulos= Articulo.order("created_at DESC")
  end

  def show
    @articulo = Articulo.find(params[:id])
    @comentario = Comment.new

    guardar_hit params[:id]
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @articulo }
    end
  end

  private
  def guardar_hit articulo_id
  #author_id equals 0 means a hit from a guest
  @hit = Hit.new(:articulo_id => articulo_id, :autor_id => 0)
  @hit.autor_id = session[:autor_id] if session[:autor_id]
  @hit.save
  end


end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def registro
    @autor= Autor.new
  end

  def ingreso
    @autor= Autor.find_by_usuario params[:usuario]
    if @autor.nil?
      redirect_to login_path, :notice => "Usuario no encontrado!"
    else
      session[:autor_id] =@autor.id
      redirect_to root_path
    end
  end

  def registrar
    @autor= Autor.new(params[:autor])
    if @autor.save
      redirect_to login_path
    else
      redirect_to registro_path, :notice => "No es posible registrarse. Campos Usuario y Nombre obligatorios, o el Usuario escogido ya no esta disponible"
    end
  end

  def salir
    session[:autor_id]=nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def loggedin_autor?
    @loggedin_autor= Autor.find(session[:autor_id]) if session[:autor_id]
    not @loggedin_autor.nil?
  end
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/autor_helper.rb
module AutorHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def get_autor articulo
    @autor = Autor.find(articulo.autor_id) if articulo.autor_id
    "#{@autor.nombre} #{@autor.apellido}"
  end
  
  def get_autor_id articulo
    @autor = Autor.find(articulo.autor_id) if articulo.autor_id
    @autor.id
  end

end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>
      <ul>
      <% @articulo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p> Categorias
    <% for category in Category.find(:all) %>
      <div>
        <%= check_box_tag "articulo[category_ids][]", category.id, @articulo.categories.include?(category) %>
        <%= category.nombre %>
      </div>
    <% end %>
  </p>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
    <%= f.label :cuerpo %><br />
    <%= f.text_area :cuerpo %>
  </div>

  <p>
  <%= hidden_field_tag :comment_ids_before_edition, @comment_ids_before_edition %>
  <%= "Comentarios:" if @articulo.comments.count > 0 %>
    <% for comment in @articulo.comments %>
      <div>
      <%= "#{comment.comentador}: '#{comment.cuerpo}'" %>
      - <%= check_box_tag "articulo[comment_ids][]", comment.id, false %> Borrar
      </div>
    <% end %>
  </p>

  <div class="actions">
    <%= f.submit "Aceptar" %>
  </div>

<% end %>

app/views/articulos/edit.html.erb
<h1>Editar articulo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @articulo %> |
<%= link_to 'Volver', articulos_path %>

app/views/articulos/index.html.erb
<h1>Mis articulos</h1>

<%= link_to 'Crear Articulo', new_articulo_path %>

<% @articulos.each do |articulo| %>
  <div class="formatted_articulo">
    <p id="fecha"><%= articulo.created_at.strftime("%A %d %h of %Y - %H:%M hs") %></p>
    <p id="titulo"><%= articulo.titulo %></p>
    <p><%= articulo.cuerpo %></p><br />
    <p id="comentarios"><%= "#{articulo.comments.count} comentarios de este articulo" if (articulo.comments.count > 0) %></p>
    <p id="comentarios"><%= "No hay comentarios de este articulo" if (articulo.comments.count == 0) %></p>
    <p id="hits"><%= "#{articulo.hits.count} visitas a este articulo" if (articulo.hits.count > 1)%></p>
    <p id="hits"><%= "#{articulo.hits.count} visita a este articulo" if (articulo.hits.count == 1)%></p>
    <p id="acciones"><%= link_to 'Ver', articulo %> |
    <%= link_to 'Editar', edit_articulo_path(articulo) %> |
    <%= link_to 'Eliminar', articulo, confirm: 'Esta seguro?', method: :delete %>
  </div>
<% end %>

app/views/articulos/new.html.erb
<h1>Crear articulo</h1>

<%= render 'form' %>

<%= link_to 'Volver', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Categorias:</b>
  <% @articulo.categories.each do |c| %>
    '<%= c.nombre %>'
  <% end %>
</p>

<p>
  <b>Titulo:</b>
  <%= @articulo.titulo %>
</p>

<p>
  <b>Cuerpo:</b>
  <%= @articulo.cuerpo %>
</p>

<p>
  <b><%= "Comentarios:" if @articulo.comments.count > 0 %></b><br/>
    <% @articulo.comments.each do |c| %>
      <%= "[#{c.comentador}] #{c.cuerpo}" %><br/>
    <% end %>
</p>

<%= link_to 'Editar', edit_articulo_path(@articulo) %> |
<%= link_to 'Volver', articulos_path %>

app/views/autor/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
		<%= @autor.usuario %>
</p>

<p>
  <b>Nombre:</b>
  <%= @autor.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @autor.apellido %>
</p>

<p>
  <b>Cantidad de articulos:</b>
  <%= @autor.articulos.count %> <br/>
</p>

<%= link_to 'Volver', root_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.nombre %></td>
    <td><%= category.descripcion %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @category.nombre %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @category.descripcion %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Noticias!</h1>
<p>Esto es lo que esta pasando cheee!</p>

<% @articulos.each do |articulo| %>
  <div class="formatted_articulo">
    <p id="fecha"><%= articulo.created_at.strftime("%A %d %h of %Y - %H:%M hs") %></p>
    <p id="titulo"><%= articulo.titulo %></p>
    <p id="autor">por <%= link_to (get_autor articulo), :controller => "autor", :action => "show", :id => (get_autor_id articulo) %></p>
    <p><%= articulo.cuerpo[0..140] %></p><br />
    <p id="hits"><%= "#{articulo.hits.count} visitas a este articulo" if (articulo.hits.count > 1)%></p>
    <p id="hits"><%= "#{articulo.hits.count} visita a este articulo" if (articulo.hits.count == 1)%></p>
    <p id="leermas"><%= link_to "leer mas...", :controller => "home", :action => "show", :id => articulo.id %></p>
  </div>
<% end %>

app/views/home/show.html.erb
<h1>Noticias!</h1>
<p>Esto es lo que esta pasando cheee!</p>

<div class="formatted_articulo">
  <p id="categorias">
  <% @articulo.categories.each do |c| %>
    (<%= c.nombre %>)
  <% end %>		
  </p>
  <p id="fecha"><%= @articulo.created_at.strftime("%A %d %h of %Y - %H:%M hs") %></p>
  <p id="titulo"><%= @articulo.titulo %></p>
  <p id="autor"><%= get_autor @articulo %></p>
  <p><%= @articulo.cuerpo %></p>
  <br />
  <p><b> <%= "Comentarios:" if @articulo.comments.count > 0 %> </b></p>
    <% @articulo.comments.each do |comment| %>
      <p id="comentador"><%= "#{comment.comentador} dice:" %></p>
      <p id="comentario"><%= comment.cuerpo %></p>
      <br/>
    <% end %>

  <p><b>Comentar sobre este articulo</b></p>
  <%= form_for @comentario, :url=>{:controller=>"articulos", :action=>"agregar_comentario"} do |f| %>
    <%= hidden_field_tag :articulo_id, @articulo.id %>
  <p>
  <%=f.label "Nombre (puede comentar anonimamente)"%><br />
  <%= f.text_field :comentador %>
  </p>
  <p>
  <%= f.label :cuerpo %><br />
  <%= f.text_area :cuerpo %>
  </p>
  <p>
  <%= f.submit "Comentar!" %>
  </p>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>AtagSummitFS</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">

<body>

  <div>
    <% flash.each do |name,msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>

  <div class= "autor_nav">
    <%= link_to "Inicio", root_path %> | 
    <% if loggedin_autor? %>
      <%= "Hola #{@loggedin_autor.nombre}#{@loggedin_autor.apellido}" %>
      <%= link_to "(Salir)", salir_path %> |    
      <%= link_to "(Mis articulos)", articulos_path %>
    <% else %>
      <%= link_to "Ingreso", login_path %> si ya tienes una cuenta, sino
      <%= link_to "Registrate", registro_path %>
    <% end %>
  </div>

  <%= yield %>

</body>

</html>

app/views/login/login.html.erb
<h1>Ingreso</h1>
<p>Ingrese su usuario</p>

<%= form_tag "/ingreso" do %>
  <p>
    <b>Usuario<b/><br />
    <%= text_field_tag :usuario %>
  </p>
  <p>
    <%= submit_tag "Ingresar" %>
  </p>
<% end %>

app/views/login/registro.html.erb
<h1>Registrarse</h1>
<p>Ingresa al fabulantástico mundo de la publicación online!!!</p>

<%= form_for @autor, :url => {:action => "registrar" } do |f| %>
  <p>
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </p>
  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </p>
  <p>
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </p>
  <p>
    <%= f.submit "Registrarse" %>
  </p>
<% end %>